sonar.projectKey=2401067_PDFhub
sonar.projectName=2401067_PDFhub
sonar.projectVersion=1.0
sonar.sources=pdfapp,project
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=sqp_5c6bcf57fec846bce3562d1d777b633b4360c411
sonar.python.coverage.reportPaths=coverage.xml

















