sonar.projectKey=PDF_IMCC
sonar.projectName=PDF_IMCC
sonar.projectVersion=1.0
sonar.sources=pdfapp,project
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.login=squ_18aed67d089b8f9f1d38c7c8d26072ecd1558b77
sonar.python.coverage.reportPaths=coverage.xml

















